[package]
name = "core"
version = "0.0.0"
edition = "2024"
publish = false

[dependencies]
candle-core = "0.9.1"
candle-nn = "0.9.1"
indicatif = "0.18.3"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.145"

#[dev-dependencies]
chrono = "0.4.42"
csv = "1.4.0"
plotters = { version = "0.3.7", default-features = false, features = ["bitmap_backend", "bitmap_encoder", "line_series", "ttf", "fontconfig-dlopen"] }
