[package]
name = "core"
version = "0.0.0"
edition = "2024"
publish = false

[dependencies]
candle-core = "0.9.1"
candle-nn = "0.9.1"
csv = "1.4.0"
eframe = "0.33.2"
egui_plot = "0.34.0"
indicatif = "0.18.3"
plotters = { version = "0.3.7", default-features = false, features = ["bitmap_backend", "bitmap_encoder", "line_series", "ttf", "fontconfig-dlopen"] }
